name: libphonenumber_desktop
description: A new Flutter project.
version: 0.0.1
homepage: A nice dream

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.41.3
  ffi: ^2.0.1
  libphonenumber_platform_interface: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^6.1.2

flutter:
  plugin:
    implements: libphonenumber_plugin
    platforms:
      linux:
        pluginClass: LibphonenumberDesktop
        dartPluginClass: LibphonenumberDesktop
      # macos:
      #   pluginClass: LibPhoneNumberDesktopPlugin
      windows:
        pluginClass: LibphonenumberDesktop
        dartPluginClass: LibphonenumberDesktop
