name: libphonenumber_desktop
description: Desktop implementation of libphonenumber_plugin
version: 0.1.0
homepage: https://github.com/leam-tech/libphonenumber_desktop
repository: https://github.com/leam-tech/libphonenumber_desktop.git

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.59.0
  ffi: ^2.0.1
  libphonenumber_platform_interface: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  ffigen: ^7.2.4

flutter:
  plugin:
    implements: libphonenumber_plugin
    platforms:
      linux:
        pluginClass: LibphonenumberDesktop
        dartPluginClass: LibphonenumberDesktop
      macos:
        pluginClass: LibphonenumberDesktop
        dartPluginClass: LibphonenumberDesktop
      windows:
        pluginClass: LibphonenumberDesktop
        dartPluginClass: LibphonenumberDesktop
