#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.59.0.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_is_valid_number_impl(
    port_: MessagePort,
    phone_number: impl Wire2Api<String> + UnwindSafe,
    region: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "is_valid_number",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_phone_number = phone_number.wire2api();
            let api_region = region.wire2api();
            move |task_callback| is_valid_number(api_phone_number, api_region)
        },
    )
}
fn wire_normalize_phone_number_impl(
    port_: MessagePort,
    phone_number: impl Wire2Api<String> + UnwindSafe,
    region: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "normalize_phone_number",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_phone_number = phone_number.wire2api();
            let api_region = region.wire2api();
            move |task_callback| normalize_phone_number(api_phone_number, api_region)
        },
    )
}
fn wire_get_region_info_impl(
    port_: MessagePort,
    phone_number: impl Wire2Api<String> + UnwindSafe,
    region: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_region_info",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_phone_number = phone_number.wire2api();
            let api_region = region.wire2api();
            move |task_callback| get_region_info(api_phone_number, api_region)
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

impl support::IntoDart for RegionInfo {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.country_code.into_dart(),
            self.formatted_phone_number.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for RegionInfo {}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
