name: Build Dynamic Libraries
on:
  workflow_dispatch:
    inputs:
      debug-ssh:
        description: "Debug SSH"
        required: false
        default: "false"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd rust && cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: RustLib
          path: rust/target/release/librust.so

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd rust && cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: RustLib
          path: |
            rust/target/release/rust.dll